// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xdSnfxWCziyzb8tBiGitqa
// Component: iHDVMRGn6s
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Dashboard from "../../Dashboard"; // plasmic-import: TCjH0W7XCS/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_fantaasta.module.css"; // plasmic-import: xdSnfxWCziyzb8tBiGitqa/projectcss
import sty from "./PlasmicAppdashboardsetting.module.css"; // plasmic-import: iHDVMRGn6s/css

export type PlasmicAppdashboardsetting__VariantMembers = {};

export type PlasmicAppdashboardsetting__VariantsArgs = {};
type VariantPropType = keyof PlasmicAppdashboardsetting__VariantsArgs;
export const PlasmicAppdashboardsetting__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAppdashboardsetting__ArgsType = {};
type ArgPropType = keyof PlasmicAppdashboardsetting__ArgsType;
export const PlasmicAppdashboardsetting__ArgProps = new Array<ArgPropType>();

export type PlasmicAppdashboardsetting__OverridesType = {
  root?: p.Flex<"div">;
  dashboard?: p.Flex<typeof Dashboard>;
};

export interface DefaultAppdashboardsettingProps {}

function PlasmicAppdashboardsetting__RenderFunc(props: {
  variants: PlasmicAppdashboardsetting__VariantsArgs;
  args: PlasmicAppdashboardsetting__ArgsType;
  overrides: PlasmicAppdashboardsetting__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Setting"}</title>
        <meta key="og:title" property="og:title" content={"Setting"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Dashboard
            data-plasmic-name={"dashboard"}
            data-plasmic-override={overrides.dashboard}
            className={classNames("__wab_instance", sty.dashboard)}
            tabs={"setting" as const}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dashboard"],
  dashboard: ["dashboard"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  dashboard: typeof Dashboard;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAppdashboardsetting__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAppdashboardsetting__VariantsArgs;
    args?: PlasmicAppdashboardsetting__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAppdashboardsetting__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAppdashboardsetting__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAppdashboardsetting__ArgProps,
      internalVariantPropNames: PlasmicAppdashboardsetting__VariantProps
    });

    return PlasmicAppdashboardsetting__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAppdashboardsetting";
  } else {
    func.displayName = `PlasmicAppdashboardsetting.${nodeName}`;
  }
  return func;
}

export const PlasmicAppdashboardsetting = Object.assign(
  // Top-level PlasmicAppdashboardsetting renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),

    // Metadata about props expected for PlasmicAppdashboardsetting
    internalVariantProps: PlasmicAppdashboardsetting__VariantProps,
    internalArgProps: PlasmicAppdashboardsetting__ArgProps
  }
);

export default PlasmicAppdashboardsetting;
/* prettier-ignore-end */
